apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask
spec:
  containers:
  - name: flask-container
    image: rubinder/flask-app:latest
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: ClusterIP
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 5500
    
# apiVersion: v1
# kind: Pod
# metadata:
#   name: flask-app
#   labels:
#     app: flask
# spec:
#   containers:
#   - name: flask-cantainer
#     image: rubinder/flask-app:latest
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: flask
#   ports:
#   - protocol: TCP
#     port: 80 
#     targetPort: 5500
