apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxflaskapp-deployment
  labels:
    app: nginxflaskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxflaskapp
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginxflaskapp
    spec:
      containers:
      - name: nginxflaskapp-container
        image: rubinder/nginxflaskapp-custom:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxflaskapp-service
spec:
  type: LoadBalancer
  selector:
    app: nginxflaskapp
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 80
    
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   containers:
#   - name: nginx-container
#     image: rubinder/nginx-custom:latest
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#   - protocol: TCP
#     port: 80 
#     targetPort: 80