apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ns}}
data:
  default.conf: |   
    server {
      listen 80;
  
      location / {
        proxy_pass http://flask-service:8080/index.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: {{ns}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: {{ns}}
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    
  # apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
#   namespace: {{ns}}
# spec:
#   replicas: 10
#   selector:
#     matchLabels:
#       app: nginx
#   strategy:
#     rollingUpdate:
#       maxSurge: 10%
#       maxUnavailable: 25%
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: eu.gcr.io/lbg-cloud-incubation/rkg-nginx-alpine:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: nginx-service
#   namespace: {{ns}}
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
    
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginxflaskapp-deployment
#   labels:
#     app: nginxflaskapp
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: nginxflaskapp
#   strategy:
#     rollingUpdate:
#       maxSurge: 10%
#       maxUnavailable: 25%
#   template:
#     metadata:
#       labels:
#         app: nginxflaskapp
#     spec:
#       containers:
#       - name: nginxflaskapp-container
#         image: eu.gcr.io/lbg-cloud-incubation/rkg-nginx-alpine:latest
#         imagePullPolicy: Always
#         ports:
#         - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginxflaskapp-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginxflaskapp
#   ports:
#   - protocol: TCP
#     port: 80 
#     targetPort: 80
    
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   labels:
#     app: nginx
# spec:
#   containers:
#   - name: nginx-container
#     image: rubinder/nginx-custom:latest
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: nginx
#   ports:
#   - protocol: TCP
#     port: 80 
#     targetPort: 80